/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class decoder_NativeDecoder */

#ifndef _Included_decoder_NativeDecoder
#define _Included_decoder_NativeDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     decoder_NativeDecoder
 * Method:    createNative
 * Signature: (Ljava/lang/String;ZZ)J
 */
JNIEXPORT jlong JNICALL Java_decoder_NativeDecoder_createNative
  (JNIEnv *, jobject, jstring, jboolean, jboolean);

/*
 * Class:     decoder_NativeDecoder
 * Method:    getFormatNative
 * Signature: (J)Ldecoder/NativeFormat;
 */
JNIEXPORT jobject JNICALL Java_decoder_NativeDecoder_getFormatNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     decoder_NativeDecoder
 * Method:    nextFrameNative
 * Signature: (JII)Ldecoder/NativeFrame;
 */
JNIEXPORT jobject JNICALL Java_decoder_NativeDecoder_nextFrameNative
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     decoder_NativeDecoder
 * Method:    seekToNative
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_decoder_NativeDecoder_seekToNative
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:     decoder_NativeDecoder
 * Method:    resetNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_decoder_NativeDecoder_resetNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     decoder_NativeDecoder
 * Method:    deleteNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_decoder_NativeDecoder_deleteNative
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
