/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118749-g0f7d77fc42-20250312"
#endif /* AVUTIL_FFVERSION_H */
