/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1-184-gdc07f98934-20250131"
#endif /* AVUTIL_FFVERSION_H */
